### ISSUE TITLE
[Feature Request]: Proxy module for Apache2 addon 

### ISSUE THREAD

**Issue by tortfeaser** [FaserF/hassio-addons#227]
### The request

Hi, thanks for the addon.

I'm trying to create an https proxy for an (internal) http site, ie access https://192.168.1.xxx:443 to see the site I can already see at http://192.168.1.107:900. (Because the HA web card can only serve https pages if ssl is setup in HA. ...107:9000 is a local media server)

I establish this in Apache2 with config:
```
<VirtualHost *:443>
 ServerName xxx.yyy.com/lms
 ServerAdmin admin@xxx.yyy.com
 
 # Turn on SSL
 SSLEngine on
 SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL
 SSLCertificateFile /ssl/certificate.crt
 SSLCertificateKeyFile /ssl/private.key
 
 # Configure the proxy
 ProxyRequests off
 RequestHeader edit Host (:\d+)?$ :443
 ProxyPreserveHost On
 ProxyPass / http://192.168.1.107:9000/ nocanon
 ProxyPassReverse / http://192.168.1.107:9000/
 AllowEncodedSlashes NoDecode
```
But I get an error `AH00526: Syntax error on line 12 of /etc/apache2/sites-enabled/000-default-le-ssl.conf:
Invalid command 'ProxyRequests', perhaps misspelled or defined by a module not included in the server configuration`

I've tried to a2enmod proxy but this simplistic solution doesn't work. How can I enable the proxy module in this addon?

### For which Add-On

Apache2

**Comment by jcerullo** [comment]
It's not completely clear what is being requested here.  But proxy server addons already exist in HA.  Here is a recommended video:Home Assistant Remote Access using NGINX.  I would suggest a proxy manager addon in this case.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Home Assistant Remote Access using NGINX


 |

 |

 |

 Saturday, November 4, 2023 at 12:55:04 AM EDT, tortfeaser ***@***.***> wrote:
 
 
 


The request

Hi, thanks for the addon.

I'm trying to create an https proxy for an (internal) http site, ie access https://192.168.1.xxx:443 to see the site I can already see at http://192.168.1.107:900. (Because the HA web card can only serve https pages if ssl is setup in HA. ...107:9000 is a local media server)

I establish this in Apache2 with config:
<VirtualHost *:443>
 ServerName xxx.yyy.com/lms
 ServerAdmin ***@***.***
 
 # Turn on SSL
 SSLEngine on
 SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL
 SSLCertificateFile /ssl/certificate.crt
 SSLCertificateKeyFile /ssl/private.key
 
 # Configure the proxy
 ProxyRequests off
 RequestHeader edit Host (:\d+)?$ :443
 ProxyPreserveHost On
 ProxyPass / http://192.168.1.107:9000/ nocanon
 ProxyPassReverse / http://192.168.1.107:9000/
 AllowEncodedSlashes NoDecode

But I get an error AH00526: Syntax error on line 12 of /etc/apache2/sites-enabled/000-default-le-ssl.conf: Invalid command 'ProxyRequests', perhaps misspelled or defined by a module not included in the server configuration

I've tried to a2enmod proxy but this simplistic solution doesn't work. How can I enable the proxy module in this addon?

For which Add-On

Apache2

Is your feature request related to a problem?

No response

Additional information

No response

**Comment by FaserF** [comment]
I am of the same opinion as jcerullo . Have you tried using the NGINX Proxy Manager addon? I think that should be the better way to do it. 

Other than that your config file seems to be faulty. Have you closed <VirtualHost *:443> in your config?
