### ISSUE TITLE
ctype extension

### ISSUE THREAD

**Issue by PM04290** [FaserF/hassio-addons#29]
Is it possible to add php extension ?
I use Fat-Free Framework PHP and it use  ctype_digit() ; when i run i have an error

`Call to undefined function ctype_digit() [/share/htdocs/lib/base.php:272]`

How to modify extension list ?

**Comment by FaserF** [comment]
I have added the ctype php7 extension. 
Please give it a new try with V2.0.4

It was added only to the apach2 Full Addon.

**Comment by PM04290** [comment]
i have uninstall the 2.0.3 and the 2.0.4 not visible at the moment, i try later.. many thanks.

**Comment by PM04290** [comment]
2.0.4 is ok for ctype.
My framework have a permission denied to create a temporary cache file, i'm noob on Linux/HA, can you tell me how to put right for you addon (and php) to access R/W on /share/htdocs/tmp ?

**Comment by FaserF** [comment]
my addon will overwrite the neccessary permissions on every addon start.
With which user are you trying to access these files?
Does the error also occure if you put these files one folder upwards (because then maybe my permission fixing part isnt working).

Can you also post the outcome from the addon log (there it displays the permissions shortly after starting the addon)

**Comment by PM04290** [comment]
it's the php script who want to create file in /tmp dir, created by my copy/paste files for put web site files, i don't know the user is

**Comment by FaserF** [comment]
Can you give a user and password within this PHP Script?

**Comment by PM04290** [comment]
i found solution with my friend google, a `CHMOD o=rw /tmp` solve the problem
thankyou for your help.
next step for me , solving the problem of link routing page, Ingress problem i think; i hope my friend will help me :)
